name: PASSING_INFORMATION
on: push
jobs:
  TESTING_INFORMATION_PASSING:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run : echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run : echo "test=world" >> "$GITHUB_OUTPUT"
  PRINTING_PASSED_INFORMATION:
    runs-on: ubuntu-latest
    needs: TESTING_INFORMATION_PASSING
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job2.outputs.output2 }}
        run: echo "${OUTPUT1} ${OUTPUT2}"

    