name: using_conditionals
on: push
jobs:
  using_conditionals:
    runs-on: ubuntu-latest
    steps:
      - name: checking_github_conditionals
        env: 
            EVENT_CONTEXT: ${{ toJSON(github.event) }}
        if: $EVENT_CONTEXT.name == 'manvinder63'
        run : echo "Hello" $EVENT_CONTEXT.name
