name: Secrets with GitHub Actions Demo
on: [push]
jobs:
  Explore-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.dockerusername }}
        run: |
          example-command "$super_secret"